In [119]:
#  Es un framework de aprendizaje profundo que proporciona
# herramientas para construir y entrenar redes neuronales
import torch
# Este módulo contiene las herramientas para definir y trabajar con capas y modelos neuronales en PyTorch
import torch.nn as nn
# Contiene los optimizadores para ajustar los pesos de los modelos durante el entrenamiento
import torch.optim as optim

from sklearn.model_selection import train_test_split
# El proceso de estandarización transforma cada característica de tal manera que tenga
# una media de 0 y una desviación estándar de 1
# Ayuda a que las características tengan la misma escala
from sklearn.preprocessing import StandardScaler
# Esta función calcula la precisión de las clasificaciones proporcionadas
from sklearn.metrics import accuracy_score
import numpy as np

import matplotlib.pyplot as plt

In [120]:
# Lectura del dataset
data = np.loadtxt("wine_preparado.csv", delimiter=",")
print(data)

[[1.000e+00 1.423e+01 1.710e+00 ... 1.040e+00 3.920e+00 1.065e+03]
 [1.000e+00 1.320e+01 1.780e+00 ... 1.050e+00 3.400e+00 1.050e+03]
 [1.000e+00 1.316e+01 2.360e+00 ... 1.030e+00 3.170e+00 1.185e+03]
 ...
 [3.000e+00 1.327e+01 4.280e+00 ... 5.900e-01 1.560e+00 8.350e+02]
 [3.000e+00 1.317e+01 2.590e+00 ... 6.000e-01 1.620e+00 8.400e+02]
 [3.000e+00 1.413e+01 4.100e+00 ... 6.100e-01 1.600e+00 5.600e+02]]


In [121]:
# Seleccionar columnas independientes y dependiente
X = data[:, 1:]
y = data[:, 0]

# Cambiamos valores de columna dependiente
y[y == 1] = 0
y[y == 2] = 1
y[y == 3] = 2

In [122]:
# imprimimos caracteristicas
X

array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]])

In [123]:
# imprimimos columna dependiente
y

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2.])

In [124]:
# imprimimos dimensiones de X y y
X.shape, y.shape

((178, 13), (178,))

In [125]:
# separamos datos de entrenamiento y de prueba, prueba en 20%
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [2]:
# Esta instancia se utilizará para calcular la media y la desviación estándar de las características
# y luego realizar la estandarización
scaler = StandardScaler()
# Se ajusta y transforma el conjunto de datos de entrenamiento con la funcion fit_transform
# Esto significa que el scaler calcula la media y la desviación estándar de cada característica
# en X_train, y luego estandariza las características de acuerdo a estas estadísticas.
# Después de esto, X_train contendrá las características estandarizadas.
X_train = scaler.fit_transform(X_train)
# Utiliza el mismo scaler para transformar el conjunto de datos de prueba con la funcion transform
# Esto es importante para garantizar que las características en el conjunto de prueba
# estén estandarizadas de la misma manera que las del conjunto de entrenamiento
X_test = scaler.transform(X_test)

# diferencia entre fit_transform y transform
# Si estás utilizando datos de entrenamiento y necesitas ajustar el transformer y transformar
# los datos al mismo tiempo, usa fit_transform.

# Si ya has ajustado el transformer previamente y solo necesitas transformar nuevos datos
# (por ejemplo, datos de prueba), usa transform.

In [128]:
# Este código crea una variable llamada device que almacena la cadena de caracteres 'cuda' si hay
# un dispositivo CUDA disponible en el sistema, y 'cpu' en caso contrario.

# torch.cuda.is_available(): Esta función de PyTorch verifica si hay un dispositivo CUDA disponible en el sistema
# Después de ejecutar esta línea de código, la variable device se puede utilizar posteriormente para
# especificar el dispositivo en el que se ejecutarán las operaciones de PyTorch. Por ejemplo, se puede
# utilizar para enviar tensores a la GPU si device es 'cuda', o para utilizar la CPU si device es 'cpu'
device = 'cuda' if torch.cuda.is_available() else 'cpu'
# En otras palabras, esta línea de código selecciona el dispositivo adecuado ('cuda' o 'cpu')
# en función de la disponibilidad de CUDA en el sistema.

# para aplicaciones que requieren un alto rendimiento en operaciones matemáticas intensivas,
# como el entrenamiento de modelos de aprendizaje profundo, CUDA y las GPU son la elección
# preferida debido a su capacidad de procesamiento masivo en paralelo

In [129]:
# Convierte el conjunto de datos en un tensor de PyTorch. torch.tensor() se utiliza para crear un
# tensor a partir de un array. dtype=torch.float o int64 especifica que se desea que el tensor resultante
# tenga tipo de datos float o int64. .to(device) envía el tensor resultante al dispositivo especificado
# por la variable device.
X_train_tensor = torch.tensor(X_train, dtype=torch.float).to(device)
y_train_tensor = torch.tensor(y_train, dtype=torch.int64).to(device)
X_test_tensor = torch.tensor(X_test, dtype=torch.float).to(device)
y_test_tensor = torch.tensor(y_test, dtype=torch.int64).to(device)

In [130]:
# Define una nueva clase llamada SimpleClassifier que hereda de nn.Module
class SimpleClassifier(nn.Module):
  # Este es el método constructor de la clase SimpleClassifier. Toma dos argumentos:
  # in_features, que representa el número de características de entrada al modelo, y out_features,
  # que representa el número de clases de salida.
  def __init__(self, in_features, out_features):
    # Llama al constructor de la clase base nn.Module, lo que inicializa la clase base y establece
    # el estado interno del modelo.
    super().__init__()
    # Define la primera capa lineal (nn.Linear) del modelo. Esta capa tiene in_features entradas y 120 salidas.
    # La capa lineal aplica una transformación lineal a los datos de entrada.
    self.layer_1 = nn.Linear(in_features,120)
    #  Define la segunda capa lineal del modelo. Esta capa toma 120 entradas de la capa anterior y produce
    # 10 salidas.
    self.layer_2 = nn.Linear(120,10)
    # Define la tercera capa lineal del modelo. Esta capa toma 10 entradas de la capa anterior y produce
    # out_features salidas, que es el número de clases de salida
    self.layer_3 = nn.Linear(10,out_features)

  # Este método define cómo se realiza la propagación hacia adelante en el modelo.
  # Toma un tensor de entrada x y devuelve un tensor de salida.
  def forward(self, x):
    # Define la secuencia de operaciones que se aplican al tensor de entrada x. Primero se pasa x
    # a través de layer_1, luego se aplica una función de activación (por defecto, lineal)
    # a la salida de layer_1. El resultado se pasa a layer_2, y luego a layer_3.
    # Esto representa una arquitectura de red neuronal feedforward de tres capas.
    x = self.layer_3(self.layer_2(self.layer_1(x)))
    return x

In [131]:
# Calcula el número de características de entrada (in_features) del conjunto de
# datos de entrenamiento X_train. X_train.shape[1] devuelve la longitud de la segunda dimensión
# de X_train, que es el número de características.
in_features = X_train.shape[1]
#  Calcula el número de clases de salida (num_classes) del conjunto de etiquetas y. set(y)
# devuelve un conjunto único de clases en y, y len() cuenta cuántas clases únicas hay en total.
num_classes = len(set(y))

# Inicializa un objeto de la clase SimpleClassifier con in_features como el número de características de entrada
# y num_classes como el número de clases de salida. Luego, se envía el modelo al dispositivo especificado por
# la variable device.
model = SimpleClassifier(in_features,num_classes).to(device)

In [132]:
# Define la función de pérdida que se utilizará para calcular
# el error del modelo durante el entrenamiento. nn.CrossEntropyLoss()
# es comúnmente utilizada en problemas de clasificación multiclase
# Esta función combina una capa Softmax y la función de pérdida de
# entropía cruzada logarítmica, que es adecuada para problemas de
# clasificación en los que se espera que cada muestra pertenezca a una sola clase.
criterion = nn.CrossEntropyLoss()
# Define el optimizador que se utilizará para ajustar los pesos del modelo durante
# el entrenamiento. En este caso, se utiliza el descenso de gradiente estocástico
# (SGD). model.parameters() devuelve los parámetros entrenables del modelo, es decir,
# los pesos de las capas lineales. El parámetro lr=0.01 especifica la tasa de aprendizaje,
# que controla el tamaño de los pasos de actualización de los pesos durante el entrenamiento.
# Un valor pequeño de la tasa de aprendizaje generalmente hace que el entrenamiento sea
# más lento pero más estable.
optimizer = optim.SGD(model.parameters(), lr=0.01)

In [133]:
# Define el número total de épocas (iteraciones) para entrenar el modelo.
num_epochs = 1000

for epoch in range(num_epochs):
  # Pone el modelo en modo de entrenamiento. Esto es importante para ciertas capas,
  # como las capas de dropout o de normalización, que se comportan de manera diferente
  # durante el entrenamiento y la evaluación
  model.train()

  # Realiza una pasada hacia adelante (forward pass) del modelo utilizando los
  # datos de entrenamiento X_train_tensor y obtiene las salidas predichas
  outputs = model(X_train_tensor)
  # Calcula la pérdida del modelo comparando las salidas predichas con las etiquetas
  # reales usando la función de pérdida definida anteriormente (criterion)
  loss = criterion(outputs, y_train_tensor)

  # Calcula las etiquetas predichas tomando el índice del valor máximo en las salidas predichas.
  # Estas etiquetas se utilizarán para calcular la precisión del modelo
  _, predicted_labels = torch.max(outputs,1)
  # Calcula el número de predicciones correctas comparando las etiquetas predichas con las etiquetas reales
  correct_predictions = (predicted_labels == y_train_tensor).sum().item()

  # Calcula el número total de muestras en el conjunto de entrenamiento
  total_samples = len(y_train_tensor)
  # Calcula la precisión del modelo dividiendo el número de predicciones
  # correctas por el número total de muestras
  acc = correct_predictions / total_samples

  # Reinicia los gradientes de todos los parámetros del modelo a cero. Esto es necesario porque
  # PyTorch acumula los gradientes en cada iteración de retropropagación
  optimizer.zero_grad()
  # Realiza la retropropagación (backpropagation) para calcular los gradientes de los parámetros
  # del modelo con respecto a la función de pérdida
  loss.backward()
  #Actualiza los parámetros del modelo utilizando el optimizador configurado previamente
  optimizer.step()

  # Imprime el progreso del entrenamiento cada 10 épocas.
  if (epoch+1)%10==0:
    # Imprime el número de época actual, la pérdida actual y la precisión del modelo en el conjunto de entrenamiento.
    print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}, Accuracy: {acc:.4f}')


Epoch [10/1000], Loss: 0.8533, Accuracy: 0.8028
Epoch [20/1000], Loss: 0.7160, Accuracy: 0.9014
Epoch [30/1000], Loss: 0.6053, Accuracy: 0.9225
Epoch [40/1000], Loss: 0.5145, Accuracy: 0.9507
Epoch [50/1000], Loss: 0.4400, Accuracy: 0.9507
Epoch [60/1000], Loss: 0.3792, Accuracy: 0.9507
Epoch [70/1000], Loss: 0.3299, Accuracy: 0.9577
Epoch [80/1000], Loss: 0.2901, Accuracy: 0.9577
Epoch [90/1000], Loss: 0.2578, Accuracy: 0.9648
Epoch [100/1000], Loss: 0.2314, Accuracy: 0.9718
Epoch [110/1000], Loss: 0.2097, Accuracy: 0.9859
Epoch [120/1000], Loss: 0.1916, Accuracy: 0.9859
Epoch [130/1000], Loss: 0.1763, Accuracy: 0.9859
Epoch [140/1000], Loss: 0.1633, Accuracy: 0.9859
Epoch [150/1000], Loss: 0.1522, Accuracy: 0.9859
Epoch [160/1000], Loss: 0.1425, Accuracy: 0.9930
Epoch [170/1000], Loss: 0.1339, Accuracy: 0.9930
Epoch [180/1000], Loss: 0.1264, Accuracy: 0.9930
Epoch [190/1000], Loss: 0.1197, Accuracy: 0.9930
Epoch [200/1000], Loss: 0.1137, Accuracy: 0.9930
Epoch [210/1000], Loss: 0.108

In [144]:
# Pone el modelo en modo de evaluación. Esto es importante para ciertas capas,
# como las capas de dropout o de normalización, que se comportan de manera diferente
# durante la evaluación que durante el entrenamiento
model.eval()

# Realiza una pasada hacia adelante (forward pass) del modelo utilizando los datos de
# prueba X_test_tensor y obtiene las salidas predichas
outputs = model(X_test_tensor)
# Calcula las etiquetas predichas tomando el índice del valor máximo en las salidas predichas
_, predicted = torch.max(outputs,1)

  # Imprimir todas las predicciones y los datos reales de prueba
print("Predicciones y datos reales de prueba:")

# Itera sobre cada muestra en el conjunto de datos de prueba
for i in range(len(X_test)):
  # Obtiene la etiqueta predicha para la muestra actual
  predicted_label = predicted[i].item()
  # Obtiene la etiqueta verdadera para la muestra actual
  true_label = y_test[i]
  # Imprime la predicción y la etiqueta verdadera para la muestra actual
  print(f"Predicción: {predicted_label}, Etiqueta verdadera: {true_label}")

# Calcular la precisión total
total_accuracy = accuracy_score(y_test, predicted.cpu().numpy())

# Convertir la precisión total a porcentaje
total_accuracy_percent = total_accuracy * 100

# Imprimir el porcentaje total de precisión
print(f"Precisión total: {total_accuracy_percent:.2f}%")

Predicciones y datos reales de prueba:
Predicción: 0, Etiqueta verdadera: 0.0
Predicción: 0, Etiqueta verdadera: 0.0
Predicción: 2, Etiqueta verdadera: 2.0
Predicción: 0, Etiqueta verdadera: 0.0
Predicción: 1, Etiqueta verdadera: 1.0
Predicción: 0, Etiqueta verdadera: 0.0
Predicción: 1, Etiqueta verdadera: 1.0
Predicción: 2, Etiqueta verdadera: 2.0
Predicción: 1, Etiqueta verdadera: 1.0
Predicción: 2, Etiqueta verdadera: 2.0
Predicción: 0, Etiqueta verdadera: 0.0
Predicción: 2, Etiqueta verdadera: 2.0
Predicción: 0, Etiqueta verdadera: 0.0
Predicción: 1, Etiqueta verdadera: 1.0
Predicción: 0, Etiqueta verdadera: 0.0
Predicción: 1, Etiqueta verdadera: 1.0
Predicción: 1, Etiqueta verdadera: 1.0
Predicción: 1, Etiqueta verdadera: 1.0
Predicción: 0, Etiqueta verdadera: 0.0
Predicción: 1, Etiqueta verdadera: 1.0
Predicción: 0, Etiqueta verdadera: 0.0
Predicción: 1, Etiqueta verdadera: 1.0
Predicción: 1, Etiqueta verdadera: 1.0
Predicción: 2, Etiqueta verdadera: 2.0
Predicción: 2, Etiqueta v